### PR TITLE
New fixes 

### PR DESCRIPTION
**Pull request by flame4ost**
Co-authored-by: flame4ost <huanmastak@gmail.com>
Co-authored-by: best-lucky1030 <bestlucky1030@gmail.com>
Co-authored-by: sleepmalc <bensoniscool123@gmail.com>

Minor bugs fixes

### CODE REVIEW

**Comment by flame4ost** [comment]
I am get pair achievements. Thank you

**Comment by flame4ost** [comment]
Create new pull request. Work

**Comment by flame4ost** [comment]
Write comment

**Comment by flame4ost** [comment]
Thank you)

**Comment by thenithinbalaji** [comment]
> lmfao. dafuq is happening here 🤣

B A D G E

**Comment by thenithinbalaji** [comment]
Locking the conversation! Feel free to contribute via PRs and issues!

**Pull request merged**
